[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.intl", "php82Extensions.bcmath", "php82Extensions.ctype", "php82Extensions.fileinfo", "php82Extensions.tokenizer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip", "npm ci"]

[phases.build]
cmds = ["npm run build", "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache", "chmod -R 775 storage bootstrap/cache", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
